### ISSUE TITLE
Sort the coordinates to get the shortest path to draw

### ISSUE THREAD

**Issue by Andreasgdp** [Andreasgdp/Drawing-robot-semester-1#26]
# To-Do
## Update simulator to match drawing robot
- [x] Draw outline using edgedetection
- [x] For each segment: Go through pixels and draw them.
- [x] Save last pixel cord and get next pixel cord to draw lines between (to check if the algorithm is segmentizing correctly)
- [x] (Maybe) Animate the process

## Segmentize image into similar colored parts
- [x] Get cords using edge-detection
- [x] Using parts of the existing sorting algorithm go through the cords of the edges and group cords that are close in each their own arrays.
- [x] Use these groups to divide all color cords into groups within the boundaries of the cords from edge-detection.

## Use sorting algorithm to go through each segment of the image and find the longest route through all pixels
- [x] Go through pixels and look for the nearest pixel
  - [x] When the nearest pixel is too far away, lift the pencil and move to the closest cord to continue
